before_install:
  - travis_retry composer self-update

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --prefer-dist

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script:
  - vendor/bin/phpunit
